// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qmTafPNirujNlpoA8oFUtTAuxul51d4',
    appId: '1:611166463193:web:23c2ba60040d89c460cac8',
    messagingSenderId: '611166463193',
    projectId: 'fastfeed-bf48f',
    authDomain: 'fastfeed-bf48f.firebaseapp.com',
    storageBucket: 'fastfeed-bf48f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3h4R_SAHaU5rtl4rfLeT4WNZPkSXkZ0',
    appId: '1:611166463193:android:988fcc0943f6aea860cac8',
    messagingSenderId: '611166463193',
    projectId: 'fastfeed-bf48f',
    storageBucket: 'fastfeed-bf48f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBemIpJ3oUp9ZBh8swsEwDUN7aiaQe9HK4',
    appId: '1:611166463193:ios:d873644f32fd68e860cac8',
    messagingSenderId: '611166463193',
    projectId: 'fastfeed-bf48f',
    storageBucket: 'fastfeed-bf48f.appspot.com',
    iosClientId: '611166463193-u7bnskat0go9meo5nlls24a1vado99n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.FastFeed',
  );
}
